Repository Nexters/moyamoya-ios-app, pull requests merged in 2024-02, with the labels that each got.

#106 [api] Delete Profile api 구현
  FunchApp.xcodeproj/project.pbxproj
  FunchApp/Core/Network/DefaultTargetType.swift
  FunchApp/Data/DataMapping/RequestDTO/DeleteProfile.Req.swift
  FunchApp/Data/DataMapping/ResponseDTO/DeleteProfile.Res.swift
  FunchApp/Data/Repository/ProfileRepository.swift
  FunchApp/Domain/Entities/Request/DeleteProfileQuery.swift
  FunchApp/Domain/Interfaces/ProfileRepositoryType.swift
  FunchApp/Domain/UseCase/Profile/DeleteProfileUseCase.swift
  FunchApp/Presentation/HomeScene/HomeView.swift
  FunchApp/Presentation/ProfileScene/ProfileView.swift
  FunchApp/Presentation/ProfileScene/ProfileViewBuilder.swift
  FunchApp/Presentation/ProfileScene/ProfileViewModel.swift
  FunchAppTests/Repositories/ProfileRepositoryTests.swift
Labels: 성민, review request

#102 [release] 1.0.0
  FunchApp.xcodeproj/project.pbxproj
  FunchApp/Core/DesignSystem/Resources/Image.xcassets/FunchIcon.appiconset/symbol.png
  FunchApp/Core/DesignSystem/Sources/UICompoents.SwiftUI/ChipButton.swift
  FunchApp/Core/DesignSystem/Sources/UICompoents.SwiftUI/FunchDropDownMenu.swift
  FunchApp/Core/DesignSystem/Sources/UICompoents.SwiftUI/FunchTextField.swift
  FunchApp/Core/DesignSystem/Sources/UICompoents.SwiftUI/SubwayChipView.swift
  FunchApp/Core/Network/DefaultTargetType.swift
  FunchApp/Data/DataMapping/RequestDTO/DeleteProfile.Req.swift
  FunchApp/Data/DataMapping/ResponseDTO/DeleteProfile.Res.swift
  FunchApp/Data/Repository/ProfileRepository.swift
  FunchApp/Data/Services/OpenURLService.swift
  FunchApp/Data/Services/Services.swift
  FunchApp/Data/Services/UserService.swift
  FunchApp/Domain/Dependency/Buildable.swift
  FunchApp/Domain/Dependency/ServiceType.swift
  FunchApp/Domain/Entities/Request/DeleteProfileQuery.swift
  FunchApp/Domain/Interfaces/ProfileRepositoryType.swift
  FunchApp/Domain/UseCase/Profile/DeleteProfileUseCase.swift
  FunchApp/Presentation/Application/FunchApp.swift
  FunchApp/Presentation/HomeScene/HomeView.swift
  FunchApp/Presentation/MatchResultScene/MatchResultView.swift
  FunchApp/Presentation/MatchResultScene/SubViews/ChemistryLabel.swift
  FunchApp/Presentation/MatchResultScene/SubViews/SubwayChemistryLabel.swift
  FunchApp/Presentation/OnboardingScene/OnboardingView.swift
  FunchApp/Presentation/ProfileEditorScene/ProfileEditorView.swift
  FunchApp/Presentation/ProfileScene/ProfileView.swift
  FunchApp/Presentation/ProfileScene/ProfileViewBuilder.swift
  FunchApp/Presentation/ProfileScene/ProfileViewModel.swift
  FunchAppTests/Info.plist
  FunchAppTests/Repositories/ProfileRepositoryTests.swift
Labels: 성민, 건우, release

#112 [gui] 매칭 실패 시 알럿 띄우기
  FunchApp/Domain/UseCase/Home/HomeUseCase.swift
  FunchApp/Presentation/HomeScene/HomeView.swift
  FunchApp/Presentation/HomeScene/HomeViewModel.swift
Labels: 성민, review request

#108 [New Features] MBTICollection, ReleaseNote, AppstoreReview
  FunchApp.xcodeproj/project.pbxproj
  FunchApp/Core/DesignSystem/Resources/Image.xcassets/icon/icon_matching.imageset/Contents.json
  FunchApp/Core/DesignSystem/Resources/Image.xcassets/icon/icon_matching.imageset/vector.png
  FunchApp/Data/PersistentStorage/UserDataStorage.swift
  FunchApp/Data/Repository/BingoMBTIRepository.swift
  FunchApp/Data/Repository/MatchingRepository.swift
  FunchApp/Data/Services/OpenURLService.swift
  FunchApp/Data/Services/Services.swift
  FunchApp/Data/Services/UserService.swift
  FunchApp/Domain/Entities/MBTI.swift
  FunchApp/Domain/Entities/MatchingInfo.swift
  FunchApp/Domain/Entities/Profile.swift
  FunchApp/Domain/UseCase/BingoBoard/BingoBoardUseCase.swift
  FunchApp/Domain/UseCase/Home/HomeUseCase.swift
  FunchApp/Presentation/Application/AppCoordinator.swift
  FunchApp/Presentation/Application/FunchApp.swift
  FunchApp/Presentation/BingoBoardScene/BingoBoardView.swift
  FunchApp/Presentation/HomeScene/HomePresentation.swift
  FunchApp/Presentation/HomeScene/HomeView.swift
  FunchApp/Presentation/HomeScene/HomeViewModel.swift
  FunchApp/Presentation/ProfileEditorScene/ProfileEditorPresentation.swift
  FunchApp/Presentation/ProfileEditorScene/ProfileEditorViewModel.swift
Labels: works, enhancement, 건우, review request, merged

#123 [Architecture] `Completion` -> `Combine`
  FunchApp.xcodeproj/project.pbxproj
  FunchApp/Data/Repository/MatchingRepository.swift
  FunchApp/Data/Repository/MatchingRepositoryImpl.swift
  FunchApp/Data/Repository/ProfileRepository.swift
  FunchApp/Data/Repository/ProfileRepositoryImpl.swift
  FunchApp/Data/Repository/SubwayStationRepository.swift
  FunchApp/Data/Repository/SubwayStationRepositoryImpl.swift
  FunchApp/Domain/Interfaces/MatchingRepository.swift
  FunchApp/Domain/Interfaces/MatchingRepositoryType.swift
  FunchApp/Domain/Interfaces/ProfileRepository.swift
  FunchApp/Domain/Interfaces/ProfileRepositoryType.swift
  FunchApp/Domain/Interfaces/SubwayStationRepository.swift
  FunchApp/Domain/Interfaces/SubwayStationRepositoryType.swift
  FunchApp/Domain/UseCase/Home/HomeUseCase.swift
  FunchApp/Domain/UseCase/Matching/MatchingUseCase.swift
  FunchApp/Domain/UseCase/Profile/CreateProfileUseCase.swift
  FunchApp/Domain/UseCase/Profile/DeleteProfileUseCase.swift
  FunchApp/Domain/UseCase/Profile/FetchProfileUseCase.swift
  FunchApp/Domain/UseCase/Subway/SearchSubwayUseCase.swift
  FunchApp/Presentation/HomeScene/HomeViewBuilder.swift
  FunchApp/Presentation/HomeScene/HomeViewModel.swift
  FunchApp/Presentation/ProfileEditorScene/ProfileEditorViewBuilder.swift
  FunchApp/Presentation/ProfileEditorScene/ProfileEditorViewModel.swift
  FunchApp/Presentation/ProfileScene/ProfileViewBuilder.swift
  FunchApp/Presentation/ProfileScene/ProfileViewModel.swift
Labels: works, enhancement, 건우, review request

#124 [release] 1.1.1
  FunchApp.xcodeproj/project.pbxproj
  FunchApp/Presentation/HomeScene/HomeView.swift
Labels: 성민, 건우, release

#130 [New Features] Added Easter egg page and modified from `services` to `inject`
  FunchApp.xcodeproj/project.pbxproj
  FunchApp/Core/DesignSystem/Resources/Image.xcassets/이스터에그/Contents.json
  FunchApp/Core/DesignSystem/Resources/Image.xcassets/이스터에그/easter_egg.imageset/Contents.json
  FunchApp/Core/DesignSystem/Resources/Image.xcassets/이스터에그/easter_egg.imageset/image 7.png
  FunchApp/Core/Inject/OpenURL/OpenURLError.swift
  FunchApp/Core/Inject/OpenURL/OpenURLPath.swift
  FunchApp/Core/Inject/OpenURL/OpenURLProvider.swift
  FunchApp/Core/Network/APIClient.swift
  FunchApp/Data/Repository/MBTIRepository.swift
  FunchApp/Data/Repository/MatchingRepositoryImpl.swift
  FunchApp/Data/Repository/ProfileRepositoryImpl.swift
  FunchApp/Data/Repository/SubwayStationRepositoryImpl.swift
  FunchApp/Data/Services/OpenURLService.swift
  FunchApp/Data/Services/Services.swift
  FunchApp/Data/Services/UserService.swift
  FunchApp/Domain/Dependency/ServiceType.swift
  FunchApp/Presentation/Application/FunchApp.swift
  FunchApp/Presentation/EasterEggScene/EasterEggView.swift
  FunchApp/Presentation/HomeScene/HomePresentation.swift
  FunchApp/Presentation/HomeScene/HomeView.swift
  FunchApp/Presentation/HomeScene/HomeViewModel.swift
  FunchApp/Presentation/MBTIBoardScene/MBTIBoardView.swift
  FunchApp/Presentation/ProfileEditorScene/ProfileEditorViewModel.swift
  FunchApp/Presentation/ProfileScene/ProfileView.swift
  FunchApp/Presentation/ProfileScene/ProfileViewModel.swift
Labels: works, enhancement, 건우, review request

#134 [Release] 1.2.0
  FunchApp.xcodeproj/project.pbxproj
Labels: 성민, 건우, release

#136 [New Feature] ShareLink
  FunchApp.xcodeproj/project.pbxproj
  FunchApp/Core/Inject/LinkStringSet.swift
  FunchApp/Core/Inject/OpenURL/OpenURLProvider.swift
  FunchApp/Presentation/EasterEggScene/EasterEggView.swift
  FunchApp/Presentation/HomeScene/HomeView.swift
  FunchApp/Presentation/HomeScene/HomeViewModel.swift
Labels: works, 건우, review request

#137 [Release] 1.3.0
  FunchApp.xcodeproj/project.pbxproj
  FunchApp/Presentation/HomeScene/HomeViewBuilder.swift
Labels: 성민, 건우, release

#139 [Memoy] DI 구조 문제로 인한 메모리 이슈
  FunchApp.xcodeproj/project.pbxproj
  FunchApp/Core/DesignSystem/Sources/KeyboardBottomPaddingModifier.swift
  FunchApp/Core/Extensions/String+.swift
  FunchApp/Core/Inject/OpenURL/OpenURLError.swift
  FunchApp/Core/Inject/OpenURL/OpenURLInject.swift
  FunchApp/Core/Inject/UserService.swift
  FunchApp/Core/Utils/LinkStringSet.swift
  FunchApp/Data/Repository/Error/RepositoryError.swift
  FunchApp/Data/Repository/MBTIRepositoryImpl.swift
  FunchApp/Data/Repository/ProfileRepositoryImpl.swift
  FunchApp/Data/Services/Services.swift
  FunchApp/Domain/Dependency/Buildable.swift
  FunchApp/Domain/Dependency/DIContainer.swift
  FunchApp/Domain/Dependency/ServiceType.swift
  FunchApp/Domain/Interfaces/MBTIRepository.swift
  FunchApp/Domain/UseCase/MBTIBoard/MBTIBoardUseCase.swift
  FunchApp/Domain/UseCase/Matching/MatchingUseCase.swift
  FunchApp/Domain/UseCase/Profile/CreateProfileUseCase.swift
  FunchApp/Domain/UseCase/Profile/DeleteProfileUseCase.swift
  FunchApp/Domain/UseCase/Profile/FetchProfileUseCase.swift
  FunchApp/Domain/UseCase/Subway/SearchSubwayUseCase.swift
  FunchApp/Presentation/Application/FunchApp.swift
  FunchApp/Presentation/EasterEggScene/EasterEggView.swift
  FunchApp/Presentation/EasterEggScene/EasterEggViewBuilder.swift
  FunchApp/Presentation/EasterEggScene/EasterEggViewModel.swift
  FunchApp/Presentation/HomeScene/HomeView.swift
  FunchApp/Presentation/HomeScene/HomeViewBuilder.swift
  FunchApp/Presentation/HomeScene/HomeViewModel.swift
  FunchApp/Presentation/MBTIBoardScene/MBTIBoardViewBuilder.swift
  FunchApp/Presentation/MBTIBoardScene/MBTIBoardViewModel.swift
  FunchApp/Presentation/MatchResultScene/MatchResultView.swift
  FunchApp/Presentation/MatchResultScene/MatchResultViewBuilder.swift
  FunchApp/Presentation/MatchResultScene/MatchResultViewModel.swift
  FunchApp/Presentation/OnboardingScene/OnboardingViewBuilder.swift
  FunchApp/Presentation/ProfileEditorScene/ProfileEditorViewBuilder.swift
  FunchApp/Presentation/ProfileEditorScene/ProfileEditorViewModel.swift
  FunchApp/Presentation/ProfileScene/ProfileView.swift
  FunchApp/Presentation/ProfileScene/ProfileViewBuilder.swift
  FunchApp/Presentation/ProfileScene/ProfileViewModel.swift
  FunchApp/Presentation/SplashScene/SplashViewBuilder.swift
Labels: works, enhancement, 건우, review request

#142 [Release] 1.4.0
  FunchApp.xcodeproj/project.pbxproj
Labels: 성민, 건우, release
