Repository Nexters/moyamoya-ios-app, pull requests merged in 2024-03, with the labels that each got.

#143 [Architecture] 프로젝트 아키텍처 확립
  FunchApp.xcodeproj/project.pbxproj
  FunchApp/Application/AppCoordinator.swift
  FunchApp/Application/Dependency.swift
  FunchApp/Application/FunchApp.swift
  FunchApp/Core/Inject/OpenURL/OpenURLInject.swift
  FunchApp/Core/Inject/UserService.swift
  FunchApp/Core/Network/APIClient.swift
  FunchApp/Data/PersistentStorage/UserDataStorage.swift
  FunchApp/Data/Repository/MBTIRepositoryImpl.swift
  FunchApp/Data/Repository/MatchingRepositoryImpl.swift
  FunchApp/Data/Repository/ProfileRepositoryImpl.swift
  FunchApp/Data/Repository/SubwayStationRepositoryImpl.swift
  FunchApp/Presentation/EasterEggScene/EasterEggView.swift
  FunchApp/Presentation/EasterEggScene/EasterEggViewBuilder.swift
  FunchApp/Presentation/EasterEggScene/EasterEggViewModel.swift
  FunchApp/Presentation/HomeScene/HomeView.swift
  FunchApp/Presentation/HomeScene/HomeViewBuilder.swift
  FunchApp/Presentation/HomeScene/HomeViewModel.swift
  FunchApp/Presentation/MBTIBoardScene/MBTIBoardViewBuilder.swift
  FunchApp/Presentation/MBTIBoardScene/MBTIBoardViewModel.swift
  FunchApp/Presentation/MatchResultScene/MatchResultViewBuilder.swift
  FunchApp/Presentation/MatchResultScene/MatchResultViewModel.swift
  FunchApp/Presentation/ProfileEditorScene/ProfileEditorViewBuilder.swift
  FunchApp/Presentation/ProfileEditorScene/ProfileEditorViewModel.swift
  FunchApp/Presentation/ProfileScene/ProfileViewBuilder.swift
  FunchApp/Presentation/ProfileScene/ProfileViewModel.swift
Labels: enhancement, 건우, review request

#144 [QA] 1차 qa 사항들 (부분)반영
  FunchApp/Application/FunchApp.swift
Labels: 성민, review request, QA: Bug

#146 [New Feature] MultiProfiles
  FunchApp.xcodeproj/project.pbxproj
  FunchApp/Application/Dependency.swift
  FunchApp/Core/DesignSystem/Sources/UICompoents.SwiftUI/FunchTextField.swift
  FunchApp/Core/Extensions/Optional+Core.swift
  FunchApp/Core/Extensions/Set+Core.swift
  FunchApp/Data/DataMapping/ResponseDTO/CreateProfile.Res.swift
  FunchApp/Data/DataMapping/ResponseDTO/GetProfileFromDeviceId.Res.swift
  FunchApp/Data/PersistentStorage/UserDataStorage.swift
  FunchApp/Data/Repository/ProfileRepositoryImpl.swift
  FunchApp/Domain/Entities/Profile.swift
  FunchApp/Presentation/HomeScene/HomePresentation.swift
  FunchApp/Presentation/HomeScene/HomeView.swift
  FunchApp/Presentation/HomeScene/HomeViewModel.swift
  FunchApp/Presentation/MBTIBoardScene/MBTIBoardView.swift
  FunchApp/Presentation/MBTIBoardScene/MBTIBoardViewModel.swift
  FunchApp/Presentation/MultiProfileScene/MultiProfileListPresentation.swift
  FunchApp/Presentation/MultiProfileScene/MultiProfileListView.swift
  FunchApp/Presentation/MultiProfileScene/MultiProfileListViewBuilder.swift
  FunchApp/Presentation/MultiProfileScene/MultiProfileListViewModel.swift
  FunchApp/Presentation/ProfileEditorScene/ProfileEditorView.swift
  FunchApp/Presentation/ProfileEditorScene/ProfileEditorViewModel.swift
  FunchApp/Presentation/ProfileScene/ProfileView.swift
  FunchApp/Presentation/ProfileScene/ProfileViewModel.swift
Labels: feature, enhancement, 건우, review request

#149 release 1.5.0
  FunchApp.xcodeproj/project.pbxproj
  FunchApp/Presentation/HomeScene/HomeView.swift
  FunchApp/Presentation/MBTIBoardScene/MBTIBoardView.swift
  FunchApp/Presentation/MatchResultScene/MatchResultView.swift
  FunchApp/Presentation/MultiProfileScene/MultiProfileListView.swift
  FunchApp/Presentation/OnboardingScene/OnboardingView.swift
  FunchApp/Presentation/ProfileEditorScene/ProfileEditorView.swift
  FunchApp/Presentation/ProfileScene/ProfileView.swift
Labels: 성민, 건우, release

#154 [Release] 1.5.1
  FunchApp.xcodeproj/project.pbxproj
Labels: 성민, 건우, release

#155 [코드 개선] SwiftUI Delegate 적용
  FunchApp.xcodeproj/project.pbxproj
  FunchApp/Application/Dependency.swift
  FunchApp/Application/FunchApp.swift
  FunchApp/Presentation/EasterEggScene/EasterEggView.swift
  FunchApp/Presentation/HomeScene/HomePresentation.swift
  FunchApp/Presentation/HomeScene/HomeView.swift
  FunchApp/Presentation/HomeScene/HomeViewBuilder.swift
  FunchApp/Presentation/HomeScene/HomeViewModel.swift
  FunchApp/Presentation/MBTIBoardScene/MBTIBoardView.swift
  FunchApp/Presentation/MatchResultScene/MatchResultView.swift
  FunchApp/Presentation/MultiProfileScene/MultiProfileListDelegate.swift
  FunchApp/Presentation/MultiProfileScene/MultiProfileListPresentation.swift
  FunchApp/Presentation/MultiProfileScene/MultiProfileListView.swift
  FunchApp/Presentation/MultiProfileScene/MultiProfileListViewBuilder.swift
  FunchApp/Presentation/MultiProfileScene/MultiProfileListViewModel.swift
  FunchApp/Presentation/ProfileEditorScene/ProfileEditorView.swift
  FunchApp/Presentation/ProfileEditorScene/ProfileEditorViewModel.swift
  FunchApp/Presentation/ProfileScene/ProfileView.swift
  FunchApp/Presentation/ProfileScene/ProfileViewBuilder.swift
  FunchApp/Presentation/ProfileScene/ProfileViewDelegate.swift
  FunchApp/Presentation/ProfileScene/ProfileViewModel.swift
Labels: enhancement, 건우

#156 [Architecture] SwiftUI Presentation Layer 구조 개선
  FunchApp.xcodeproj/project.pbxproj
  FunchApp/Application/Dependency.swift
  FunchApp/Application/FunchApp.swift
  FunchApp/Presentation/EasterEggScene/EasterEggView.swift
  FunchApp/Presentation/HomeScene/HomePresentation.swift
  FunchApp/Presentation/HomeScene/HomeView.swift
  FunchApp/Presentation/HomeScene/HomeViewBuilder.swift
  FunchApp/Presentation/HomeScene/HomeViewModel.swift
  FunchApp/Presentation/MBTIBoardScene/MBTIBoardView.swift
  FunchApp/Presentation/MatchResultScene/MatchResultView.swift
  FunchApp/Presentation/MultiProfileScene/MultiProfileListDelegate.swift
  FunchApp/Presentation/MultiProfileScene/MultiProfileListPresentation.swift
  FunchApp/Presentation/MultiProfileScene/MultiProfileListView.swift
  FunchApp/Presentation/MultiProfileScene/MultiProfileListViewBuilder.swift
  FunchApp/Presentation/MultiProfileScene/MultiProfileListViewModel.swift
  FunchApp/Presentation/ProfileEditorScene/ProfileEditorView.swift
  FunchApp/Presentation/ProfileEditorScene/ProfileEditorViewModel.swift
  FunchApp/Presentation/ProfileScene/ProfileView.swift
  FunchApp/Presentation/ProfileScene/ProfileViewBuilder.swift
  FunchApp/Presentation/ProfileScene/ProfileViewDelegate.swift
  FunchApp/Presentation/ProfileScene/ProfileViewModel.swift
Labels: enhancement, 건우, review request

#159 [Release] 1.5.2
  FunchApp.xcodeproj/project.pbxproj
Labels: 건우, release
